[package]
name = "library_dev_extras"
version = "0.1"
path = "src"

[dependencies]
library_dev = {git = "https://github.com/dselsam/library_dev.git", rev = "9e9009034de6e32e3eaf9f3e8a58d2d02e534617"}
